72 backend comments
kilkeny/blur pull request #107
Opened 2021-08-30 23:59 UTC by Ortiz1221

Закроет #72

2021-08-31 17:26 UTC, imkopyova approved these changes

2021-08-31 18:23 UTC, AirMust commented on client/components/ForumCard/index.tsx
> +        <Typography variant="body1">comments: {comments ? comments.length : 0}</Typography>
`comments?.length ?? 0` можно так

2021-08-31 18:24 UTC, AirMust commented on client/components/Message/index.tsx
> +      dispatch(removeCommentThunk({ commentid: parseInt(id, 10), topicid }));
давай  сделаем так? 
`const commentid: parseInt(id, 10)`
`dispatch(removeCommentThunk({ commentid, topicid }));`

2021-08-31 19:06 UTC, AirMust reviewed
Когда

2021-08-31 19:06 UTC, aimustaev commented on client/core/store/reducers/forum.reducer.ts
> +    return state.map((topic) => (topic.id === payload.topicid
Так делать не нужно, для всех операций есть `action`,всю обработку лучше вынести туда

2021-08-31 19:06 UTC, AirMust commented on client/pages/Discussion/index.tsx
> +  const dispatch = useDispatch();
была такая строчка мб она нужна? чтоб при обновлении страницы все ок было 
`const { id } = useParams<{ id: string }>();`

2021-09-01 15:52 UTC, Ortiz1221 commented on client/components/Message/index.tsx
> +      dispatch(removeCommentThunk({ commentid: parseInt(id, 10), topicid }));
Так будет ругаться из-за того, что выше есть другая переменная с такими именем. Затенение получится. Можно вынести выше в переменную targetId, но это кажется лишним

2021-09-01 15:52 UTC, Ortiz1221 commented on client/pages/Discussion/index.tsx
> +  const dispatch = useDispatch();
Она есть, просто переехала на пару строчек ниже

2021-09-01 16:21 UTC, nickchamel requested changes

2021-09-01 16:21 UTC, nickchamel commented on client/components/ForumCard/index.tsx
> +        <Typography variant="body1">comments: {comments ? comments.length : 0}</Typography>
А можно и просто `{comments.length}`, если тип пропсы `comments: []`
А если `comments?: []`, то можно дефолтное значение указать в аргументах `comments = []`

2021-09-01 16:21 UTC, nickchamel commented on client/components/Message/index.tsx
> +      dispatch(removeCommentThunk({ commentid: parseInt(id, 10), topicid }));
А что с camelCase? `commentid` `topicid`
Дальше по коду они так же пишутся, и в моделях в том числе, какая-то проблема с ними?
sequelize вроде позволяет camelCase использовать

2021-09-01 16:21 UTC, nickchamel commented on client/core/store/store.types.tsx
>    content: string,
в том ревью вроде писал об этом месте - тут можно поправить оформление

2021-09-01 16:21 UTC, nickchamel commented on client/pages/Discussion/index.tsx
> +    reset();
о таких моментах тоже писал в ревью)

2021-09-01 16:21 UTC, nickchamel commented on server/controllers/ForumController.ts
> +    const { topicid, author, content, created } = req.body;
и о таких) Я не знаю,  что у вас там по времени, что вы будете исправлять, что нет, но я в любом случае все отписываю что есть.
Кстати если есть время, то для валидации советую посмотреть в сторону https://github.com/typestack/class-validator

2021-09-01 17:26 UTC, Ortiz1221 commented on client/components/Message/index.tsx
> +      dispatch(removeCommentThunk({ commentid: parseInt(id, 10), topicid }));
Если бы... Пробовала и camelCase и snake_case, но в итоге таблица всё равно приводилась к нижнему регистру. На решение конкретно этой проблемы потратила два вечера, способов заморозить имена именно колонок так и не нашла. В итоге остановилась на нижнем регистре. Это лучше, чем нерабочий код(

2021-09-01 17:27 UTC, Ortiz1221 commented on client/components/Message/index.tsx
> +      dispatch(removeCommentThunk({ commentid: parseInt(id, 10), topicid }));
@nickchamel  Пробовала и camelCase и snake_case, но в итоге таблица всё равно приводилась к нижнему регистру. На решение конкретно этой проблемы потратила два вечера, способов заморозить имена именно колонок так и не нашла. В итоге остановилась на нижнем регистре. Это лучше, чем нерабочий код(

2021-09-01 17:57 UTC, nickchamel commented on client/components/Message/index.tsx
> +      dispatch(removeCommentThunk({ commentid: parseInt(id, 10), topicid }));
Таблица и будет приводится к нижнему регистру) postgres не поддерживает camelCase. Просто как правило либы сами делают change case. Ну да ладно, 2 вечера много действительно)

2021-09-01 18:40 UTC, nickchamel approved these changes

2021-09-01 19:49 UTC, merged